swagger: "2.0"
info:
  title: Student Management System Api
  description: A REST api that manages the student's database
  version: 1.0.0

basePath: /api

consumes:
  - application/json
produces:
  - application/json

paths:
  /login:
    post:
      tags: [Login]
      operationId: sms.users.login
      summary: User authentication
      description: Tries to login in the user while returning a token
      parameters:
        - in: body
          name: user
          schema:
            type: object
            required:
              - username
              - password
            properties:
              username:
                type: string
              password:
                type: string
      responses:
        200:
          description: Returns the user specific token
          schema:
            type: object
            properties:
              token:
                type: string

  /personal_info:
    get:
      operationId: sms.personal_info.get
      summary: Personal_info query
      description: Gets a student or a group of students bio data
      parameters:
        - name: mat_no
          in: query
          type: string
          required: false
      responses:
        200:
          description: Returns the bio data for the student or group of students
          schema:
            $ref: '#/definitions/PersonalInfo'
        404:
          description: Mat no does not exist

    post:
      operationId: sms.personal_info.post
      parameters:
        - name: student_data
          in: body
          required: true
          schema:
            $ref: '#/definitions/PersonalInfo'
      responses:
        200:
          description: Record successfully added

  /course_details:
    get:
      operationId: sms.course_details.get
      parameters:
        - in: query
          name: course_code
          type: string
          required: true
      responses:
        200:
          description: Success
          schema:
            $ref: '#/definitions/CourseDetails'

    post:
      operationId: sms.course_details.post
      parameters:
        - in: body
          name: course
          schema:
            $ref: '#/definitions/CourseDetails'
      responses:
        200:
          description: Success



definitions:
  PersonalInfo:
    type: object
    properties:
      mat_no:
        type: string
      surname:
        type: string
      othernames:
        type: string
      mode_of_entry:
        type: integer
      session_admitted:
        type: integer
      current_level:
        type: integer
      sex:
        type: string
      date_of_birth:
        type: string
      state_of_origin:
        type: string
      phone_no:
        type: string
      email_address:
        type: string
      sponsor_phone_no:
        type: string
      sponsor_email_address:
        type: string
      grad_stats:
        type: integer

  CourseDetails:
    type: object
    properties:
      course_code:
        type: string
      course_title:
        type: string
      course_credit:
        type: integer
      course_semester:
        type: integer
      course_level:
        type: integer
      teaching_dept:
        type: string